import puppeteer from 'puppeteer-core';
const b = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', args: ['--no-sandbox','--headless=new'] });
const pg = await b.newPage();
await pg.setViewport({ width: 390, height: 844, deviceScaleFactor: 2, isMobile: true });
await pg.goto('http://localhost:3939/', { waitUntil: 'networkidle0', timeout: 30000 });
await new Promise(r => setTimeout(r, 2500));
await pg.screenshot({ path: '/tmp/mobile-music.png' });
await pg.click('.hub-typenav button:nth-child(3)');
await new Promise(r => setTimeout(r, 1800));
await pg.screenshot({ path: '/tmp/mobile-movies.png' });
await b.close();
console.log('done');
